config/routes.rb
Planit::Application.routes.draw do
  resources :users

  resources :events

  match '/sms', to: 'receive_text#index', :via => :post

  root :to => "welcome#home"

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  attr_accessible :active, :event_id, :user1_id, :user2_id

  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :details, :end, :location, :start, :title, :audience, :organizedBy

  has_many :users
  has_many :conversations

  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :cell, :event_id, :gender, :name, :preference

  belongs_to :event

  validates_presence_of :name, :event_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    parseTimes params
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    parseTimes params

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def parseTimes params
    date = params[:date] ? params[:date].split("/") : []
    start_time = params[:start] ? params[:start].split(":") : []
    end_time = params[:end] ? params[:end].split(":") : []

    if (date.length > 2) && (start_time.length > 0) then
      params[:event][:start] = Time.new(date[2], date[0], date[1], start_time[0], start_time.length > 1 ? start_time[1] : 0).to_s
    else
      params[:event][:start] = ""
    end
    if (date.length > 2) && (end_time.length > 0) then
      #extra_day = end_time[0] < start_time[0] ? 1 : 0
      #extra_day = 1 if end_time[0] == start_time[0] && end_time[1] < start_time[1]
      params[:event][:end] = Time.new(date[2], date[0], date[1], end_time[0], end_time.length > 1 ? end_time[1] : 0).to_s
    else
      params[:event][:end] = ""
    end
  end

end

app/controllers/receive_text_controller.rb
class ReceiveTextController < ApplicationController
  def index
    message_body = params["Body"]
    from_number = params["From"]

    twilio_sid = 'ACd6e2cd138e425cc622425573e6216494'
    twilio_token = '{{ 900a14db17298034ba0707d3dd7c48f5 }}'
    twilio_phone_number = '5005550006'
    

    User.create(:name => "TWILIO THING", :event_id => 3)
    #@twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

    #@twilio_client.account.sms.messages.create(
      #:from => "+1#{twilio_phone_number}",
      #:to => from_number,
      #:body => "This is a message for #{from_number}. I got your message even tho im a bot"
    #)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    if (@user = User.find_by_cell(params[:user][:cell]))
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to @user, notice: 'RSVP\'d successfully!' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      @user = User.new(params[:user])
      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'RSVP\'d successfully!' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
#! ruby -Ku

class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def format_time t
    t.localtime.strftime("%H:%M")
  end

  def format_date d
    d.localtime.strftime("%a %b %d %Y")
  end
end

app/helpers/receive_text_helper.rb
module ReceiveTextHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div id="step1">
    Step 1: Fill in as much as you want.
      <%= f.submit "", :class => "doneButton", :style => "position: relative; top: -30px;"%>
  </div>

  <%= f.text_field :title, :id => "title", :class => "textField", :autocomplete => "off", :placeholder => "Untitled Event" %><br>
  <%= f.text_field :organizedBy, :id => "organizedBy", :class => "textField", :autocomplete => "off", :placeholder => "Who's is it organized by?" %><br>

  <div class="entry">
    Date and Time:
  </div>

   <div class="field" style="margin-left: 20px;">
    <%= text_field_tag :date,
      @event.start ? @event.start.strftime("%m/%d/%Y") : '',
      :autocomplete => "off",
      :onkeyup => "putDayInNext(this)",
      :placeholder => DateTime.now.strftime("%m/%d/%Y"),
      :class => "dateSelect textField entry" %>
    ( <%= label_tag :dayOfWeek,
      (format_date (@event.start ?  @event.start : Time.now)),
      :style => "font-size: 14px" %> )
  </div>

  <div id="calendar">
        <div id="cont"></div>
  </div>
  <script type="text/javascript">
    var LEFT_CAL = Calendar.setup({
      cont: "cont",
      weekNumbers: false,
      selectionType: Calendar.SEL_MULTIPLE,
      showTime: 12
    })

    function initCalendar() {
      LEFT_CAL.fdow = 0;
      LEFT_CAL.args.showTime = false;
      LEFT_CAL.redraw();
    };

    initCalendar();

    LEFT_CAL.addEventListener("onSelect", function(){
      var ta = jQuery("#date");
      ta.val(this.selection.print("%m/%d/%Y").join("\n"));
    });

  </script>

  <div class="field entry">
   from <%= text_field_tag :start,
    (format_time (@event.start ? @event.start : Time.now)),
      :class => "timeSelect textField entry", :style => "width: 68px;", :placeholder => format_time(Time.now) %>
    until  <%= text_field_tag :end,
    (format_time (@event.end ? @event.end : Time.now + 1.hour)),
    :class => "timeSelect textField entry", :style => "width: 68px;", :placeholder => format_time(Time.now + 1.hour) %>
    <%= label_tag :dayOfWeek,
      (format_date (@event.start ?  @event.start
                                 : Time.now)),
      :style => "font-size: 11px" %>
    <br />
  </div>
 
  <div class="entry" style="margin-bottom: 10px; margin-top: 20px;">
    Location:
  </div>

  <div class="field entry">
    <%= f.text_field :location, :class => "entry textField", :autocomplete => "off", :placeholder => "e.g. Philadelphia" %>
    <%= button_tag  "Search", {:class => "link", :type => "button", :onclick => "codeAddress()"} %>
    <br />
  <div id="suggestion" style="display:inline-block;top:0;padding:2px;display:none"
    onclick="jQuery('#event_location').val(jQuery('#suggestion').html())">Carnegie Mellon</div>
  </div>
  <br />
  <div id="map_canvas" style="width:698px; height:300px"></div>
  <br />

  <div class="field">
    <%= f.text_area :details, :id => "moreInfo", :class => "textField", :placeholder => "Add more info..." %>
  </div>
  <div class="actions">
      <%= f.submit "", :class => "doneButton" %>
      <a href="#"></a>
  </div>
<% end %>

app/views/events/_view.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div id="step1" style="float: none; margin-bottom: 40px;">
    Step 2: Share the URL to your friends!
  </div>
  <div id="title">
    <%= @event.title %>
  </div>
  <br>
  <div id="organizedBy">
    <%= @event.organizedBy %>
  </div>
  <br>

  <div class="entry">
    Date and Time:
  </div>

   <div class="field" style="margin-left: 20px;">
    <%= text_field_tag :date,
      @event.start ? @event.start.strftime("%m/%d/%Y") : '',
      :autocomplete => "off",
      :onkeyup => "putDayInNext(this)",
      :placeholder => DateTime.now.strftime("%m/%d/%Y"),
      :class => "dateSelect textField entry" %>
    ( <%= label_tag :dayOfWeek,
      (format_date (@event.start ?  @event.start : Time.now)),
      :style => "font-size: 14px" %> )
  </div>

  <div class="field entry">
   from <%= text_field_tag :start,
    (format_time (@event.start ? @event.start : Time.now)),
      :class => "timeSelect textField entry", :style => "width: 68px;", :placeholder => format_time(Time.now) %>
    until  <%= text_field_tag :end,
    (format_time (@event.end ? @event.end : Time.now + 1.hour)),
    :class => "timeSelect textField entry", :style => "width: 68px;", :placeholder => format_time(Time.now + 1.hour) %>
  </div>
 
  <div class="entry" style="margin-bottom: 10px; margin-top: 20px;">
    Location:
  </div>

  <div class="field entry" id="event_location">
    <%= @event.location %>
    <br />
    <script type="text/javascript">
        var ta = display();
    </script>
  <div id="suggestion" style="display:inline-block;top:0;padding:2px;display:none"
    onload"jQuery('#event_location').val(jQuery('#suggestion').html())">Carnegie Mellon</div>
  </div>
  <br />
  <div id="map_canvas" style="width:698px; height:300px"></div>
  <br />

  <div id="moreInfo">
    <%= @event.details %>
  </div>

  <%= link_to 'Edit', edit_event_path(@event), :class => "link", :type => "button", :style => "float: right; margin-bottom: 40px;" %>
<% end %>

app/views/events/edit.html.erb
<div id="createEventWrapper">
	<%= render 'form' %>
</div>

<div id="logo_div">
	<%= link_to image_tag("logo.png", :id => "logo", :alt => "plan.it"), root_path %>
</div>
<div id="footernote">
	Created as part of PennApps 2013 - Willy Hauser & Mirai Akagawa
</div>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Start</th>
    <th>End</th>
    <th>Location</th>
    <th>Details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.start %></td>
  <td><%= event.end %></td>    
    <td><%= event.location %></td>
    <td><%= event.details %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div id="createEventWrapper">
	<%= render 'form' %>
</div>

<div id="logo_div">
	<%= link_to image_tag("logo.png", :id => "logo", :alt => "plan.it"), root_path %>
</div>
<div id="footernote">
	Created as part of PennApps 2013 - Willy Hauser & Mirai Akagawa
</div>

app/views/events/show.html.erb
<div id="createEventWrapper">
  <p id="notice"><%= notice %></p>
  <%= render 'view' %>
</div>

<div id="logo_div">
  <%= link_to image_tag("logo.png", :id => "logo", :alt => "plan.it"), root_path %>
</div>
<div id="footernote">
  Created as part of PennApps 2013 - Willy Hauser & Mirai Akagawa
</div>

<%= link_to new_user_path(:k => @event.id), new_user_path(:k => @event.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>- plan.it -</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "stylesheet", :media => "all" %>
  <%= stylesheet_link_tag    "jscal2", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jscal2" %>
  <%= javascript_include_tag "calendar" %>
  <%= javascript_include_tag "en" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCW3GbI73C08axB354lE1hJI9spmuBLxJA&sensor=true">
  </script>
  <script type="text/javascript">
    var geocoder, map;
    function initialize() {
      var mapOptions = {
        center: new google.maps.LatLng(40.4230, -98.7372),
        zoom: 3,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      geocoder = new google.maps.Geocoder();
      map = new google.maps.Map(document.getElementById("map_canvas"),
        mapOptions);
    }

    function autofill() {
      var address = document.getElementById("event_location").value;
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          var zoom = 20;
          if(results[0].geometry.bounds) {
            var west = results[0].geometry.bounds.getSouthWest().lng();
            var east = results[0].geometry.bounds.getNorthEast().lng();
            var angle = east - west;
            if (angle < 0) {
              angle += 360;
            }
            zoom = Math.round(Math.log(300*360/angle/256) / Math.LN2);
          }
          map.setZoom(zoom);
          map.panTo(results[0].geometry.location);
          jQuery("#suggestion").html(results[0].formatted_address);
        }
      });
    }
    function search() {
      var address = document.getElementById("event_location").value;
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          var west = results[0].geometry.bounds.getSouthWest().lng();
          var east = results[0].geometry.bounds.getNorthEast().lng();
          var angle = east - west;
          if (angle < 0) {
            angle += 360;
          }
          var zoom = Math.round(Math.log(300*360/angle/256) / Math.LN2);
          map.setZoom(zoom);
          map.panTo(results[0].geometry.location);
          jQuery("#event_location").val(results[0].formatted_address);
          jQuery("#suggestion").hide();
          var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
          });
        }
      });
    }
  </script>
</head>
<body onload="initialize()">
  <div id="wrapper">
    <div id="bodyWrapper">
      <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cell %><br />
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.radio_button :gender, 0 %>
    male
    <br />
    <%= f.radio_button :gender, 1 %>
    female
  </div>
  <div class="field">
    <%= f.label :preference %><br />
    <%= f.radio_button :preference, 0 %>
    male
    <br />
    <%= f.radio_button :preference, 1 %>
    female
    <br />
    <%= f.radio_button :preference, 2 %>
    I don't care
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Cell</th>
    <th>Gender</th>
    <th>Preference</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.cell %></td>
    <td><%= user.gender %></td>
    <td><%= user.preference %></td>
    <td><%= user.event_id %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>RSVP</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Cell:</b>
  <%= @user.cell %>
</p>

<p>
  <b>Gender:</b>
  <%= @user.gender %>
</p>

<p>
  <b>Preference:</b>
  <%= @user.preference %>
</p>

<p>
  <b>Event:</b>
  <%= @user.event_id %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/home.html.erb
<div id="start_button_div" class="centered">
    <%= link_to image_tag("start_button.png", :id => "start_button", :alt => "start!"), new_event_path %>
</div>
<div id="slogans" class="centered">
    <div id="slogan1">
        plan, share, enjoy
    </div>
    <div id="slogan2">
        events
    </div>
    <div id="slogan3">
        the easy way.
    </div>
</div>
<div id="logo_div" style="margin-top: 90%">
    <%= link_to image_tag("logo.png", :id => "logo", :alt => "plan.it"), root_path %>
</div>
<div id="footernote">
    Created as part of PennApps 2013 - Willy Hauser & Mirai Akagawa
</div>